name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'  # Cache Yarn dependencies
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies and build
        run: yarn install --frozen-lockfile && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIDEO_COMPRESSOR_D6B5E }}"
          channelId: live
          projectId: video-compressor-d6b5e